const express = require('express');
const cors = require('cors');
const db = require('./db');
const puppeteer = require('puppeteer');

const app = express();
app.use(cors());
app.use(express.json());

// 1. Generate Construction Roadmap (Itinerary) Endpoint
app.post('/api/itinerary/generate', (req, res) => {
  const { projectType, budget, location } = req.body;
  
  // Logic to generate a custom construction timeline/roadmap
  const roadmap = {
    title: `Project Roadmap: ${projectType} in ${location}`,
    days: [
      { day: 1, activity: "Site Survey and Soil Testing" },
      { day: 5, activity: "Foundation Excavation" },
      { day: 14, activity: "Structural Walling begins" }
    ],
    estimatedPrice: budget * 0.95, // Example calculation
    compliance: "NCA Category 5 requirements applied"
  };

  res.json(roadmap);
});

// 2. PDF Generation Endpoint (Project Proposals/Guides)
app.post('/api/itinerary/pdf', async (req, res) => {
  try {
    const browser = await puppeteer.launch({
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    const page = await browser.newPage();
    
    const { title, content } = req.body.itinerary || { title: "Frah Spaces Guide", content: [] };
    
    const html = `
      <div style="font-family: Arial; padding: 40px;">
        <h1 style="color: #c29d59;">${title}</h1>
        <p>Generated by Frah Spaces Limited - Professional Construction Services</p>
        <hr />
        <div style="margin-top: 20px;">${JSON.stringify(content)}</div>
      </div>
    `;

    await page.setContent(html);
    const pdf = await page.pdf({ format: 'A4', printBackground: true });
    
    await browser.close();
    res.contentType("application/pdf");
    res.send(pdf);
  } catch (error) {
    res.status(500).json({ error: "PDF Generation Failed" });
  }
});

// 3. Material Pricing/Calculation Endpoint
app.post('/api/pricing/calculate', (req, res) => {
  const { type, length, width, subType } = req.body;
  const area = length * width;
  
  // Server-side logic for the Material Estimator
  let quantity = 0;
  if (type === 'flooring') {
    const coverage = subType === '60x60' ? 1.44 : 1.92;
    quantity = Math.ceil((area * 1.1) / coverage);
  }

  res.json({
    value: quantity,
    unit: type === 'flooring' ? "Boxes" : "Units",
    timestamp: new Date().toISOString()
  });
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => console.log(`Frah Spaces Backend running on port ${PORT}`));